### ISSUE TITLE
Agregar iconos a las redes sociales

### ISSUE THREAD

**Issue by estebanrfp** [estebanrfp/myp-layout#4]
Para mejorar un poco la estructura he pensado en incorporar iconos a las redes sociales que figuran en la información de contacto.

**Comment by estebanrfp** [comment]
Cierro este Issue, gracias por el aporte

**Comment by aguja2013** [comment]
Gracias, seguiré proponiendo. Quiero practicar el uso de git y me pareció muy buena tu propuesta.

**Comment by estebanrfp** [comment]
Me parece estupenda idea, estoy trabajando en varios proyectos, algunos privados, si en algún momento quieres participar, podría incluirte para trabajar directamente si te interesa la temática,, he hecho ya deploy total en server con repositorios bare, y es increíble las ventajas de trabajar a través  de git.
si necesitas ayuda con alguna repo, genera issue también con mi nombre, y da por hecho, que tendrás a la brevedad los resultados, al menos conmigo es así, pocos dominan git, son importante las practicas y adquirir destreza, asiduidad.
un abrazo.

**Comment by aguja2013** [comment]
Me encantaría participar, si puedes incluirme, estaré agradecido en aportar con lo que sea. 
Seguramente necesitaré ayuda en mis proyectos, te doy gracias por tu ofrecimiento y poder contar con tu colaboración, ya te avisaré. un abrazo, seguimos en contacto

**Comment by estebanrfp** [comment]
Hola, mira,  estoy a punto de subir a Github un proyecto en el que estamos trabajando, es una terminal, que simula comandos de consola, puro css3 y javascript,  la propuesta es hacer una versión de portfolio que en vez de presionar opciones para visualizar contenido, escribes los comandos y se visualiza la información en un monitor futurista con texto plano y efecto mecanográfico, te voy a incluir si quieres, esta bueno porque es solo Fontend y estarás trabajando en un proyecto real, que luego serás parte de el junto con nosotros.

Dime si te animas y te agrego, ya que el proyecto estará en una repo privada :-)
Esteban
